config/routes.rb
Rails.application.routes.draw do
  

  resources :posted_shifts

  resources :shifts

  resources :trades

  get 'calendar/index'

  get 'registrations/new'
  get 'pick_up' => 'posted_shifts#pick_up'
  get 'registrations/create'
  get 'new_trade' => 'trades#new'
  get 'trades' => 'trades#index'
  post "trades" => 'trades#index'

  resources :microposts

  root 'staticpages#home'
  get 'dashboard/index'

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :profiles, :only => [:edit, :update, :show]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :profile
  validates :content, presence: true, length: { maximum: 400 }
end

app/models/posted_shift.rb
class PostedShift < ActiveRecord::Base
	belongs_to :shift, :dependent => :destroy
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user, :dependent => :destroy
	has_many :shifts, foreign_key: "current_owner"
	has_many :shift_for_sell, :class_name => "PostedShift", :foreign_key => "seller_id", :dependent => :destroy
	has_many :microposts, :dependent => :destroy

	def fullname
		"#{fname} #{lname}"
	end
end

app/models/shift.rb
class Shift < ActiveRecord::Base
	belongs_to :user
	has_one :posted_shift, foreign_key:"st_id" 
	before_save :adjust_time_and_date
	POSITIONS = [['Z1 GATES'], ['Z2 GATES'], ['Z3 GATES'], ['Z4 GATES'], ['CKIN DC'], ['CKIN US'], ['CKIN IT']]


	def self.confirm_trade(seller)
		attrs = ["position", "date", "start_time", "finish_time", "original_owner"]
		self.new(seller.attributes_and_values(attrs))
	end

	def attributes_and_values(array)
		result = Hash.new
		array.each do |name|
			result[name] = self.attributes[name]
		end
		result
	end
	
	def adjust_time_and_date
		self.start_time = DateTime.parse("#{date.to_date.to_s} #{start_time.to_s(:time)}")
		self.finish_time = DateTime.parse("#{date.to_date.to_s} #{finish_time.to_s(:time)}")
	end

	def overlaps?(other)
		(start_time - other.finish_time) * (other.start_time - finish_time) > 0
	end

	def as_json(options = {})
    {
      :id => self.id,
      :title => self.position,
      :start => start_time,
      :end => finish_time,
   
    }
  end
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	has_many :shifts, :through => :posted_shifts 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  after_create :build_profile

  has_many :shifts, foreign_key: "current_owner"

  def build_profile
    biding,pr
  	s = SecureRandom.urlsafe_base64(8)
  	Profile.create(user: self, :p_id => s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_up_path_for(resource)
  	edit_profile_path(resource)
  end
  
  def after_sign_in_path_for(resource)
 	dashboard_index_path	
  end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
	before_filter :authenticate_user!
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
   respond_to :html
  def index
  	@microposts = Micropost.all
    respond_with(@microposts)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @microposts = Micropost.all
    respond_with(@microposts)
  end

  def show
    respond_with(@micropost)
  end

  def new
    @micropost = Micropost.new
    respond_with(@micropost)
  end

  def edit
  end

  def create
    @micropost = Micropost.new(micropost_params)
    @micropost.user_id = current_user.id 
    @micropost.save
    respond_with(@micropost)
  end

  def update
    @micropost.update(micropost_params)
    respond_with(@micropost)
  end

  def destroy
    @micropost.destroy
    redirect_to dashboard_index_path
  end

  private
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:fname, :lname, :qualifications, :location, :about)
    end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_shift, only: [:show, :edit, :update, :destroy, :trade]

  respond_to :html, :json, :xml

  def index
    @shifts = Shift.all.where(:current_owner => current_user.id)
    respond_with(@shifts)
  end

  def show
    #@shift = Shift.find(params[:id])
    respond_with(@shift)
  end

  def new
    @shift = Shift.new
    respond_with(@shift)
  end

  def edit
  end

  def create
    @shift = Shift.new(shift_params)
    @shift.original_owner = @shift.current_owner = current_user.id
    @shift.shift_posted = "Not Posted"
    if @shift.save
      flash[:notice] = "Shift Successfully Created."
    end
    respond_with(@shift)
  end

  def trade
    @profile = Profile.all
  end 

  def update
    @shift = Shift.find_by(params[:id])
    if @shift.update(shift_params)
      flash[:notice] = "Shift Successfully Updated."
    end
    respond_with(@shift)
  end

  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy
    respond_with(@shift)
  end

  private
    def set_shift
      @shift = Shift.find_by(params[:id])
    end

    def shift_params
      params.require(:shift).permit(:position, :date, :start_time, :finish_time, :original_owner, :current_owner, :shift_id, :shift_posted)
    end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @trades = Trade.all
    respond_with(@trades)
  end

  def show
    respond_with(@trade)
  end

  def new
    @trade = Trade.new
    respond_with(@trade)
  end

  def edit
  end

  def create
    @trade = Trade.new(trade_params)
    @trade.save
    respond_with(@trade)
  end

  def update
    @trade.update(trade_params)
    respond_with(@trade)
  end

  def destroy
    @trade.destroy
    respond_with(@trade)
  end

  private
    def set_trade
      @trade = Trade.find(params[:id])
    end

    def trade_params
      params.require(:trade).permit(:shift_id, :seller_id, :buyer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def profile_user
		current_user.profile
	end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/posted_shifts_helper.rb
module PostedShiftsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/microposts/_form.html.erb
<%= simple_form_for @micropost, html: {class: "well col-sm-6 col-md-4 form-horizontal"} do |f| %>
      <% if @micropost.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

          <ul>
          <% @micropost.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h4>What's New</h4>
        <div class="form-group" style="padding:14px;">
          <%= f.input :content, placeholder: "Update your status", label: false  %>
        </div>
        <%= f.submit "Post", :class => "btn btn-primary pull-right" %>
    
    <% end %>

app/views/microposts/_index.html.erb
<div class="col-md-3">
  <%= link_to "New Post", new_micropost_path, :class => "btn btn-default" %>
</div>
<div class="col-md-6 well">
      
   <% @microposts.each do |micropost| %>
      <div class="panel panel-default shadowing" style="margin: 10px">
        <div class="panel-heading"><h5 class="panel-title"><%= profile_user.fullname %></h5></div>
          <div class="panel-body">
              <%= micropost.content %>
            <hr>
          </div>
          <div class="panel-footer" >
            <ul class="list-unstyled pull-right" style="margin-bottom: 3px">
              <li><%= link_to 'Show', micropost%></li>
              <li><%= link_to 'Edit', edit_micropost_path(micropost) %></li>
              <li><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></li></ul>
            </div>
        </div>
  <% end %>

</div>
<div class="col-md-3"></div>
     

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path, {:class => "btn btn-default"}%>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/profiles/_form.html.erb
<%= form_for(@profile ) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "First Name"%><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label "Last Name" %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :qualifications %><br>
    <%= f.text_field :qualifications %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Qualifications</th>
      <th>Location</th>
      <th>About</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.fname %></td>
        <td><%= profile.lname %></td>
        <td><%= profile.qualifications %></td>
        <td><%= profile.location %></td>
        <td><%= profile.about %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @profile.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @profile.lname %>
</p>

<p>
  <strong>Qualifications:</strong>
  <%= @profile.qualifications %>
</p>

<p>
  <strong>Location:</strong>
  <%= @profile.location %>
</p>

<p>
  <strong>About Me:</strong>
  <%= @profile.about %>
</p>

<%= link_to "Edit Profile", edit_profile_path(profile_user.id), {:class => "btn btn-default"} %>

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <%= f.error_notification %>

  
  <div class="row">
    <div class="col-md-3">
      <%= f.input :position, as: :select do %>
        <%=f.select:position, Shift::POSITIONS %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :date, as: :date, as: :string, :input_html => { :value => f.object.date.blank? ? '' : f.object.date.to_date.to_s(:long) }  %>
    </div>
  </div>

  <div class="row">
    <div class="columns col-md-2">
      <%= f.input :start_time, as: :time, as: :string, :input_html => { :value => f.object.start_time.blank? ? '' : f.object.start_time.to_s(:time)  }%>
    </div>
  </div>

  <div class="row">
    <div class="columns col-md-2">
    <%= f.input :finish_time, as: :time, as: :string, :input_html => { :value => f.object.finish_time.blank? ? '' : f.object.finish_time.to_s(:time) } %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <%= f.input :shift_posted %>
    </div>
  </div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<h1>Listing shifts</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Date</th>
      <th>Start stime</th>
      <th>Finish time</th>
      <th>Original owner</th>
      <th>Current owner</th>
      <th>Shift</th>
      <th>Shift posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.position %></td>
        <td><%= shift.date.to_date.to_s(:long) %></td>
        <td><%= shift.start_time.to_s(:time) %></td>
        <td><%= shift.finish_time.to_s(:time) %></td>
        <td><%= shift.original_owner %></td>
        <td><%= shift.current_owner %></td>
        <td><%= shift.shift_id %></td>
        <td><%= shift.shift_posted %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @shift.position %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shift.date.to_date.to_s(:long) %>
</p>

<p>
  <strong>Start stime:</strong>
  <%= @shift.start_time.to_s(:time) %>
</p>

<p>
  <strong>Finish time:</strong>
  <%= @shift.finish_time.to_s(:time) %>
</p>

<p>
  <strong>Original owner:</strong>
  <%= @shift.original_owner %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @shift.shift_id %>
</p>

<p>
  <strong>Shift posted:</strong>
  <%= @shift.shift_posted %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %> |
<%= link_to 'Post Shift', new_posted_shift_path(:sid => @shift.shift_id, :pid => @shift.current_owner) %>

app/views/shifts/trade.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @shift.position %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shift.date.to_date.to_s(:long) %>
</p>

<p>
  <strong>Start stime:</strong>
  <%= @shift.start_time.to_s(:time) %>
</p>

<p>
  <strong>Finish time:</strong>
  <%= @shift.finish_time.to_s(:time) %>
</p>

<p>
  <strong>Original owner:</strong>
  <%= @shift.original_owner %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @shift.shift_id %>
</p>

<p>
  <strong>Shift posted:</strong>
  <%= @shift.shift_posted %>
</p>

app/views/trades/_form.html.erb
<%= simple_form_for(@trade) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :shift_id %>
    <%= f.input :seller_id %>
    <%= f.input :buyer_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <thead>
    <tr>
      <th>Shift</th>
      <th>Seller</th>
      <th>Buyer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.shift_id %></td>
        <td><%= trade.seller_id %></td>
        <td><%= trade.buyer_id %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shift:</strong>
  <%= @trade.shift_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @trade.seller_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @trade.buyer_id %>
</p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>