config/routes.rb
Rails.application.routes.draw do
  

  resources :posted_shifts

  resources :shifts

  resources :trades

  get 'calendar/index'

  get 'registrations/new'
  get 'pick_up' => 'posted_shifts#pick_up'
  get 'registrations/create'
  get 'new_trade' => 'trades#new'
  get 'trades' => 'trades#index'
  post "trades" => 'trades#index'

  resources :microposts

  root 'staticpages#home'
  get 'dashboard/index'

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :profiles, :only => [:edit, :update, :show]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :profile
  validates :content, presence: true, length: { maximum: 400 }
end

app/models/posted_shift.rb
class PostedShift < ActiveRecord::Base
	belongs_to :shift, :dependent => :destroy
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user, :dependent => :destroy
	has_many :shifts, foreign_key: "current_owner"
	has_many :shift_for_sell, :class_name => "PostedShift", :foreign_key => "seller_id", :dependent => :destroy
	has_many :microposts, :dependent => :destroy

	def fullname
		"#{fname} #{lname}"
	end
end

app/models/shift.rb
class Shift < ActiveRecord::Base
	belongs_to :user
	has_one :posted_shift, foreign_key:"st_id" 
	before_save :adjust_time_and_date
	POSITIONS = [['Z1 GATES'], ['Z2 GATES'], ['Z3 GATES'], ['Z4 GATES'], ['CKIN DC'], ['CKIN US'], ['CKIN IT']]


	def self.confirm_trade(seller)
		attrs = ["position", "date", "start_time", "finish_time", "original_owner"]
		self.new(seller.attributes_and_values(attrs))
	end

	def attributes_and_values(array)
		result = Hash.new
		array.each do |name|
			result[name] = self.attributes[name]
		end
		result
	end
	
	def adjust_time_and_date
		self.start_time = DateTime.parse("#{date.to_date.to_s} #{start_time.to_s(:time)}")
		self.finish_time = DateTime.parse("#{date.to_date.to_s} #{finish_time.to_s(:time)}")
	end

	def overlaps?(other)
		(start_time - other.finish_time) * (other.start_time - finish_time) > 0
	end

	def as_json(options = {})
    {
      :id => self.id,
      :title => self.position,
      :start => start_time,
      :end => finish_time,
   
    }
  end
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	has_many :shifts, :through => :posted_shifts 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  after_create :build_profile

  has_many :shifts, foreign_key: "current_owner"

  def build_profile
    biding,pr
  	s = SecureRandom.urlsafe_base64(8)
  	Profile.create(user: self, :p_id => s)
  end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
	before_filter :authenticate_user!
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:fname, :lname, :qualifications, :location, :about)
    end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_shift, only: [:show, :edit, :update, :destroy, :trade]

  respond_to :html, :json, :xml

  def index
    @shifts = Shift.all.where(:current_owner => current_user.id)
    respond_with(@shifts)
  end

  def show
    #@shift = Shift.find(params[:id])
    respond_with(@shift)
  end

  def new
    @shift = Shift.new
    respond_with(@shift)
  end

  def edit
  end

  def create
    @shift = Shift.new(shift_params)
    @shift.original_owner = @shift.current_owner = current_user.id
    @shift.shift_posted = "Not Posted"
    if @shift.save
      flash[:notice] = "Shift Successfully Created."
    end
    respond_with(@shift)
  end

  def trade
    @profile = Profile.all
  end 

  def update
    @shift = Shift.find_by(params[:id])
    if @shift.update(shift_params)
      flash[:notice] = "Shift Successfully Updated."
    end
    respond_with(@shift)
  end

  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy
    respond_with(@shift)
  end

  private
    def set_shift
      @shift = Shift.find_by(params[:id])
    end

    def shift_params
      params.require(:shift).permit(:position, :date, :start_time, :finish_time, :original_owner, :current_owner, :shift_id, :shift_posted)
    end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @trades = Trade.all
    respond_with(@trades)
  end

  def show
    respond_with(@trade)
  end

  def new
    @trade = Trade.new
    respond_with(@trade)
  end

  def edit
  end

  def create
    @trade = Trade.new(trade_params)
    @trade.save
    respond_with(@trade)
  end

  def update
    @trade.update(trade_params)
    respond_with(@trade)
  end

  def destroy
    @trade.destroy
    respond_with(@trade)
  end

  private
    def set_trade
      @trade = Trade.find(params[:id])
    end

    def trade_params
      params.require(:trade).permit(:shift_id, :seller_id, :buyer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def profile_user
		current_user.profile
	end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/posted_shifts_helper.rb
module PostedShiftsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ESTCv2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%- # <p class="notice"><%= notice </p><p class="alert"><%= alert </p>%>
    <!--<nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <%= link_to 'ESTC-CEPE', root_path, {:class => "navbar-brand"} %> </div>
               
    <div class="row">
            <div class="col-md-2 left-sidebar">
                <nav class="main-nav">

                </nav>
            </div>
    </div>-->

  <div class="wrapper">
    <div class="box">
        <div class="row row-offcanvas row-offcanvas-left">
                      
          
            <!-- sidebar -->
            <div class="column col-sm-2 col-xs-1 sidebar-offcanvas" id="sidebar">
              
                <ul class="nav">
                    <li><a href="#" data-toggle="offcanvas" class="visible-xs text-center"><i class="glyphicon glyphicon-chevron-right"></i></a></li>
                </ul>
               
                <ul class="nav hidden-xs" id="lg-menu">
                     <li  data-toggle="collapse" data-target="#products" class="collapsed active">

                    <li><%= link_to() do %>
                        <i class="fa fa-exchange"></i> Trades
                        <% end %>
                        <ul class="nav nav-second-level collapse-in">
                            <li><%= link_to "Pick Up", posted_shifts_path %> </li>
                        </ul>       
                    </li>
                    <li><%= link_to(dashboard_index_path) do %>
                        <i class="fa fa-rss"></i> News
                        <% end %>
                    </li>
                    <li><%= link_to(calendar_index_path, method: :get) do %>
                        <i class="fa fa-calendar"></i> Calendar
                        <% end %>
                    </li>
                    <li><a href="#stories"><i class="glyphicon glyphicon-list"></i> Stories</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-paperclip"></i> Saved</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-refresh"></i> Refresh</a></li>
                </ul>
                <ul class="list-unstyled hidden-xs" id="sidebar-footer">
                    <li>
                      <h3><%= link_to 'ESTC-CEPE', root_path %></h3>
                    </li>
                </ul>
              
                <!-- tiny only nav-->
              <ul class="nav visible-xs" id="xs-menu">
                    <li><%= link_to(calendar_index_path, method: :get) do %>
                        <i class="fa fa-calendar"></i>
                        <% end %>
                    </li>
                    <li><a href="#featured" class="text-center"><i class="glyphicon glyphicon-list-alt"></i></a></li>
                    <li><a href="#stories" class="text-center"><i class="glyphicon glyphicon-list"></i></a></li>
                    <li><a href="#" class="text-center"><i class="glyphicon glyphicon-paperclip"></i></a></li>
                    <li><a href="#" class="text-center"><i class="glyphicon glyphicon-refresh"></i></a></li>
                </ul>
              
            </div>
            <!-- /sidebar -->
          
            <!-- main right col -->
            <div class="column col-sm-10 col-xs-11" id="main">
                
                <!-- top nav -->
                 <nav class="navbar navbar-inverse nav-color">
                    <div class="container-fluid">
                        <div class="navbar-header text-change">
                        <%= link_to 'ESTC-CEPE', root_path, {:class => "navbar-brand"} %> </div>
                         <% if signed_in? %>
                    <ul class="nav navbar-nav navbar-right text-change">
                        <li><%= link_to(profile_path(profile_user.id)) do %>
                            <i class="fa fa-user"></i> <%= profile_user.fullname %>
                        <% end %>
                        </li>

                        <li><%= link_to(destroy_user_session_path, method: :delete) do %>
                            <i class="fa fa-sign-out"></i> Logout
                        <% end %>
                        </li>
                    </ul>
                <% else %>
                    <ul class="nav navbar-nav navbar-right text-change">
                        <li><%= link_to(new_user_registration_path) do %>
                            <i class="fa fa-user-plus"></i> Sign Up
                        <% end %>
                        </li>

                        <li><%= link_to(new_user_session_path) do %>
                            <i class="fa fa-sign-in"></i> Login
                        <% end %>
                        </li>
                    </ul>
                <% end %>
        </div>
    </nav>
                      
                        <!-- content -->                      
                      <div class="row">
                      <%= yield %>
      </div>
  </div>
  </div>
</div>

<script type="text/javascript">
    
    $('[data-toggle=offcanvas]').click(function() {
    $(this).toggleClass('visible-xs text-center');
    $(this).find('i').toggleClass('glyphicon-chevron-right glyphicon-chevron-left');
    $('.row-offcanvas').toggleClass('active');
    $('#lg-menu').toggleClass('hidden-xs').toggleClass('visible-xs');
    $('#xs-menu').toggleClass('visible-xs').toggleClass('hidden-xs');
    $('#btnShow').toggle();
});
</script>
</body>
</html>