config/routes.rb
Rails.application.routes.draw do
  

  resources :posted_shifts

  resources :shifts

  resources :trades

  get 'calendar/index'

  get 'registrations/new'
  get 'pick_up' => 'posted_shifts#pick_up'
  get 'registrations/create'
  get 'new_trade' => 'trades#new'
  get 'trades' => 'trades#index'
  post "trades" => 'trades#index'

  resources :microposts

  root 'staticpages#home'
  get 'dashboard/index'

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :profiles, :only => [:edit, :update, :show]

end

app/models/posted_shift.rb
class PostedShift < ActiveRecord::Base
	belongs_to :shift, :dependent => :destroy
end

app/controllers/posted_shifts_controller.rb
class PostedShiftsController < ApplicationController
  before_action :set_posted_shift, only: [:show, :edit, :update, :destroy]
  before_action :set_pick_up, only: [:pick_up]
  respond_to :html

  def index
    @posted_shifts = PostedShift.all.where(:status => "Not Traded")
    respond_with(@posted_shifts)
  end

  def show
    respond_with(@posted_shift, :location => posted_shifts_url)
  end

  def new 
    @shift = Shift.find_by(params[:id]) 
    @posted_shift = PostedShift.new
    @posted_shift.st_id = params[:sid]
    respond_with(@posted_shift, :location => @posted_shifts_path)
  end 

  def edit
  end

  def create
    @user = Profile.find(current_user.id)
    @shift = @user.shifts.find_by(params[:id])
    @posted_shift = PostedShift.new(posted_shift_params)
    @posted_shift.seller_id = current_user.id
    @posted_shift.st_id = @shift.id
    @shift.shift_posted = "Posted"
    if @posted_shift.save && @shift.save
      flash[:notice] = "Shift Posted For Trade"
    end
    respond_with(@posted_shift, :location => @posted_shifts_path)
  end

  def update
    @posted_shift.update(posted_shift_params)
    respond_with(@posted_shift)
  end

  def destroy
    @posted_shift.destroy
    respond_with(@posted_shift)
  end

  def pick_up
=begin If click on pick up this trade shift object 
      @buyer = Profile.find_by(:user_id => current_user.id)
      @shift = Shift.find(params[:sid])
      @bshift = @buyer.shifts.find_by(:date => @shift.date)
      if @bshift.nil? or !@bshift.overlaps?(@shift) 
        @trade = Shift.confirm_trade(@shift)
        @trade.current_owner = current_user.id
        @trade.shift_posted = "Not Posted"
        if @trade.save
          @shift.destroy
           @posted_shifts.status = "Traded"
        end 
        respond_with(@trade, :location => shifts_url)
      end
=end
      @buyer = Profile.find_by(:user_id => current_user.id)
      @shift = Shift.find(params[:sid])
      @bshift = @buyer.shifts.find_by(:date => @shift.date)
      if @bshift.nil? or !@bshift.overlaps?(@shift) 
        @shift.current_owner = @buyer.user_id
        @shift.shift_posted =  "Not Posted"
        @shift.posted_shift.status = "Traded"
        if @shift.save && @shift.posted_shift.save
          flash[:notice] = "Shift Traded"
        end
      end
  end 

  private
    def set_posted_shift
      @posted_shift = PostedShift.find(params[:id])
    end
    
    def set_pick_up
      @posted_shift = PostedShift.find_by(:id => params[:sid])
    end
    
    def posted_shift_params
      params.require(:posted_shift).permit(:position, :date, :start_time, :finish_time, :seller_id, :buyer_id, :status)
    end
end

app/helpers/posted_shifts_helper.rb
module PostedShiftsHelper
end

app/views/posted_shifts/_form.html.erb
<%= simple_form_for(@posted_shift) do |f| %>
  <%= f.error_notification %>

  
  <div class="row">
    <div class="col-md-3">
      <%= f.input :position,input_html:{value: @shift.position}, readonly: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :date, as: :date, as: :string, input_html:{value: @shift.date.to_date.to_s(:long)} %>
    </div>
  </div>

  <div class="row">
    <div class="columns col-md-2">
      <%= f.input :start_time, as: :time, as: :string,input_html:{value: @shift.start_time.to_s(:time)} %>
    </div>
  </div>

  <div class="row">
    <div class="columns col-md-2">
    <%= f.input :finish_time, as: :time, as: :string, input_html:{value: @shift.finish_time.to_s(:time)}%>
    </div>
  </div>
  
  <div class="row">
    <div class="columns col-md-2">
    <%= f.input :st_id, input_html:{value: @shift.shift_id}%>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-3">
      <%= f.input :status %>
    </div>
  </div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posted_shifts/_form2.html.erb
<%= simple_form_for(@posted_shift) do |f| %>
  <%= f.error_notification %>

  
  <div class="row">
    <div class="col-md-3">
      <%= f.input :position,input_html:{value: @posted_shift.position}, readonly: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :date, as: :date, as: :string, input_html:{value: @posted_shift.date.to_date.to_s(:long)} %>
    </div>
  </div>

  <div class="row">
    <div class="columns col-md-2">
      <%= f.input :start_time, as: :time, as: :string,input_html:{value: @posted_shift.start_time.to_s(:time)} %>
    </div>
  </div>

  <div class="row">
    <div class="columns col-md-2">
    <%= f.input :finish_time, as: :time, as: :string, input_html:{value: @posted_shift.finish_time.to_s(:time)}%>
    </div>
  </div>
  
  <div class="row">
    <div class="columns col-md-2">
    <%= f.input :st_id, input_html:{value: @posted_shift.st_id}%>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-3">
      <%= f.input :status %>
    </div>
  </div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posted_shifts/edit.html.erb
<h1>Editing posted_shift</h1>

<%= render 'form2' %>

<%= link_to 'Show', @posted_shift %> |
<%= link_to 'Back', posted_shifts_path %>

app/views/posted_shifts/index.html.erb
<h1>Shift For Sale</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Position</th>
      <th>Date</th>
      <th>Start time</th>
      <th>Finish time</th>
      <th>Seller</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posted_shifts.each do |posted_shift| %>
      <tr>
        <td><%= posted_shift.position %></td>
        <td><%= posted_shift.date.to_date.to_s(:long) %></td>
        <td><%= posted_shift.start_time.to_s(:time) %></td>
        <td><%= posted_shift.finish_time.to_s(:time) %></td>
        <td><%= posted_shift.seller_id %></td>
        <td><%= posted_shift.status %></td>

        <% if posted_shift.seller_id == current_user.id %>
          <td><%= link_to 'Show', posted_shift %></td>
          <td><%= link_to 'Edit', edit_posted_shift_path(posted_shift.st_id) %></td>
          <td><%= link_to 'Destroy', posted_shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to 'Show', posted_shift %></td>
          <td><%= link_to 'Pick Up', pick_up_path(:sid => posted_shift.st_id, :uid => posted_shift.seller_id) %></td>
         <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posted shift', new_posted_shift_path %>

app/views/posted_shifts/new.html.erb
<h1>New posted_shift</h1>

<%= render 'form' %>

<%= link_to 'Back', posted_shifts_path %>

app/views/posted_shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @posted_shift.position %>
</p>

<p>
  <strong>Date:</strong>
  <%= @posted_shift.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @posted_shift.start_time %>
</p>

<p>
  <strong>Finish time:</strong>
  <%= @posted_shift.finish_time %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @posted_shift.seller_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @posted_shift.buyer_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @posted_shift.status %>
</p>

<%= link_to 'Edit', edit_posted_shift_path(@posted_shift) %> |
<%= link_to 'Back', posted_shifts_path %>